sudo: true
language: java
jdk:
  - oraclejdk8
deploy:
  - provider: script
    script: bash ./deploy.sh
    on:
      branch: dev

cache:
  directories:
    - $HOME/.m2

before_deploy:
  - sudo apt-get update
  - sudo apt-get install systemd
  - sudo apt-get install sshpass