server:
  port: 8889
  servlet:
    context-path: "/infotouch-feed"

hse:
  site:
    persons:
      request:
        endpoint: "/org/persons"
        timeout: 60000
        params:
          letter: "ltr"
          city: "udept"
    url: "https://www.hse.ru"