spring:
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://62.109.23.105:5432/infotouch?reWriteBatchedInserts=true
    username: infotouch
    password: infotouch2020

ruz:
  api:
    url: http://92.242.58.221/ruzservice.svc/
    schedule:
      max:
        days: 180
hse:
  site:
    persons:
      request:
        endpoint: "/org/persons"
        timeout: 60000
        params:
          letter: "ltr"
          city: "udept"
    url: "https://www.hse.ru"